"""
Reads the fu and fau tables in api.sqlite3,
and dumps them as fu.csv and fau.csv for human inspection.

Note:
    The fu and fau tables are generated by consolidate.py.

Usage:
    python dump_to_csv.py
"""

import csv
import sqlite3

if __name__ == '__main__':
  db = sqlite3.connect('api.sqlite3')
  cursor = db.cursor()

  with open('fu.csv', 'wb') as csvfile:
    cursor.execute('SELECT func_id, utter FROM fu ORDER BY func_id')
    writer = csv.writer(csvfile)
    writer.writerow(['Function','Utterance'])
    writer.writerows(cursor.fetchall())

  with open('fau.csv', 'wb') as csvfile:
    cursor.execute('SELECT func_id, arg, utter FROM fau ORDER BY func_id, arg')
    writer = csv.writer(csvfile)
    writer.writerow(['Function', 'Argument', 'Utterance'])
    writer.writerows(cursor.fetchall())

  db.close()
  print 'Done'
